window.TIMETABLE_SUBJECT_NAME_MAP = {
      "j_polski": "Język polski",
      "j_angielski": "Język angielski",
      "j_niemiecki": "Język niemiecki",
      "historia": "Historia",
      "wos": "Wiedza o społeczeństwie",
      "matematyka": "Matematyka",
      "fizyka": "Fizyka",
      "chemia": "Chemia",
      "biologia": "Biologia",
      "geografia": "Geografia",
      "informatyka": "Informatyka",
      "wf": "Wychowanie fizyczne",
      "e_dla_bezp": "Edukacja dla bezpieczeństwa",
      "zaj z wych": "Zajęcia z wychowawcą",
      "r_matematyka": "Matematyka",
      "religia": "Religia",
      "t_utk": "Urządzenia techniki komputerowej",
      "t_syst op": "Systemy operacyjne",
      "p_pr st i ob": "Programowanie strukturalne i obiektowe",
      "t_ukł an": "Układy analogowe",
      "t_ukł cyf": "Układy cyfrowe",
      "t_masz elek": "Maszyny elektryczne",
      "t_inst elekt": "Instalacje elektryczne",
      "t_pod mechat": "Podstawy mechatroniki",
      "t_rys techn": "Rysunek techniczny",
      "t_urz i mech": "Urządzenia i systemy mechatroniczne",
      "t_jęz an z": "Język angielski zawodowy",
      "t_dz gosp": "Działalność gospodarcza",
      "t_elekt i e": "Elektrotechnika i elektronika",
      "t_urz i in e": "Urządzenia i instalacje elektroniczne",      
      "t_eksp urz el": "Eksploatacja urządzeń elektronicznych",
      "t_syst mikrp": "Systemy mikroprocesorowe",
      "p_pom el i e": "Pomiary elektryczne i elektroniczne",
      "t_użyt i el": "Użytkowanie instalacji elektrycznych",
      "t_obsł maszyn": "Obsługa maszyn i urządzeń elektrycznych",
      "t_lok s kom": "Lokalne sieci komputerowe",
      "t_wit i ap i": "Witryny i aplikacje internetowe",
      "t_lok s b d": "Lokalne systemy baz danych",
      "p_eks u t k": "Eksploatacja urządzeń techniki komputerowej",
      "p_adm s op": "Administracja systemami operacyjnymi",
      "p_eks l s k": "Eksploatacja lokalnych sieci komputerowych",
      "p_tw i a b d": "Tworzenie i administrowanie bazami danych",
      "p_tw s i a i": "Tworzenie stron i aplikacji internetowych",
      "t_p t i k m": "Podstawy technologii i konstrukcji mechanicznych",
      "kszt komp zaw": "Kształcenie kompetencji zawodowych",
      "p_pr el i el": "Pracownia elektrotechniki i elektroniki",
      "t_podst aut": "Podstawy automatyki",
      "hist i teraź": "Historia i teraźniejszość",
      "t_s i s komp": "Systemy i sieci komputerowe",
      "t_podst pr": "Podstawy programowania",
      "p_tw a m i w": "Projektowanie aplikacji mobilnych i webowych",
      "t_multim": "Multimedia",
      "p_tw ap desk": "Tworzenie aplikacji desktopowych",
      "p_tw ap mob": "Tworzenie aplikacji mobilnych",
      "p_tw ap zaaw": "Zaawansowane tworzenie aplikacji",
      "bizn i zarz": "Biznes i zarządzanie",
      "e_zdrowotna": "Edukacja zdrowotna",
      "e_obywatel.": "Edukacja obywatelska",      
      "ckz":"Zajęcia w pracowniach CKZ",
    };

    window.TIMETABLE_SUBJECT_WORD_ABBREVIATION_MAP = {
      "język": "j.",
      "podstawy": "pod.",
      "programowania": "program.",

    };